### PR TITLE
feat(level): add default level in config from the builder

### PR DESCRIPTION
**Pull request by JeanBarriere**
- [x] add level into config builder
- [x] add level into config params

---
**Note** default level is TRACE (ALL)

### CODE REVIEW

**Comment by JeanBarriere** [comment]
This closes #2 and improves #6

**Comment by colelawrence** [comment]
Looks good! Just need you to rename "level" to "max_level" in all spots. That's something I discussed with the tracing team awhile back.

**Comment by JeanBarriere** [comment]
@colelawrence  max or min ?

**Comment by JeanBarriere** [comment]
@colelawrence feedback applied

**Pull request merged**
