### PR TITLE
update tracing subscriber to 0.3

### PR DESCRIPTION
**Pull request by mockersf**
update `tracing-subscriber` to the latest version

### CODE REVIEW

**Comment by colelawrence** [comment]
Acknowledged. We'll look towards publishing with this, this week. Thanks for your PR

**Review by colelawrence — APPROVED** [review]
LGTM

**Comment by colelawrence** [comment]
Published as `0.2.1`

**Comment by mockersf** [comment]
Thanks for the quick merge!

Could you yank the `0.2.1` and republish as a `0.3.0`? Changing the version of `tracing-subscriber` is a breaking change from Rust point of view, as you're using some of `tracing-subscriber` types in your exposed functions and they are not compatible between two versions.

**Pull request merged**
